"""add dossier tables

Revision ID: ee0442b52fa4
Revises: 013ad5825535
Create Date: 2026-05-05 18:44:54.120595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0442b52fa4'
down_revision: Union[str, None] = '013ad5825535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossier_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('folder', sa.String(length=50), nullable=False),
    sa.Column('subfolder', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_mentioned', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_mentioned', sa.DateTime(timezone=True), nullable=False),
    sa.Column('times_mentioned', sa.Integer(), nullable=False),
    sa.Column('source_session_ids', sa.JSON(), nullable=False),
    sa.Column('source_message_ids', sa.JSON(), nullable=False),
    sa.Column('superseded_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['superseded_by'], ['dossier_facts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dossier_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dossier_facts_folder'), ['folder'], unique=False)
        batch_op.create_index(batch_op.f('ix_dossier_facts_user_id'), ['user_id'], unique=False)

    op.create_table('dossier_checkpoints',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('last_processed_message_id', sa.String(length=36), nullable=True),
    sa.Column('last_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('facts_extracted_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_processed_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('dossier_quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fact_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['dossier_facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dossier_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dossier_quotes_fact_id'), ['fact_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dossier_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dossier_quotes_fact_id'))

    op.drop_table('dossier_quotes')
    op.drop_table('dossier_checkpoints')
    with op.batch_alter_table('dossier_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dossier_facts_user_id'))
        batch_op.drop_index(batch_op.f('ix_dossier_facts_folder'))

    op.drop_table('dossier_facts')
    # ### end Alembic commands ###
