"""remove branch column from chat_sessions

Revision ID: d27b817b65b5
Revises: ec525c63d213
Create Date: 2026-05-06 13:05:45.925230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27b817b65b5'
down_revision: Union[str, None] = 'ec525c63d213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_column('branch')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.VARCHAR(length=1), nullable=True))

    # ### end Alembic commands ###
